# operators/aap/01-namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: aap
  labels:
    openshift.io/cluster-monitoring: "true"   # recomendado por docs
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
