# operators/aap/03-subscription.yaml
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ansible-automation-platform
  namespace: aap
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  channel: stable-2.4             # ← AJUSTA al canal vigente en tu cluster
  installPlanApproval: Manual     # control fino de upgrades (recomendado)
  name: ansible-automation-platform-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace